### PR TITLE
Added a wiki-style page navigator based on header indentation

### PR DESCRIPTION
**Pull request by coolcat1711**
So, not quite new content additions but I made a sort of wiki-style header that automatically pulls from the available headers on a page to make everything linkable.

Considering that we were talking about having instructions embedded on pages, I figured it might be worthwhile to sketch out what navigating that might look like.

Plus, there should hopefully be enough of a framework here to adapt this in a couple different ways for the actual instructions sections.

Thoughts?

Also hoping to actually get around to fleshing out more of the page contents itself in the near future, but my schedule might push that into next week...

### CODE REVIEW

**Comment by Aesistril** [comment]
Yeah this looks okay. I would have prefered a pure html aproach but you've got some serious js work here plus this piece of js is not crucial for viewing the page and it is a much more dynamic approach.

However the styling is a little broken on mobile and I don't like the border being the same as top level ones, though I can fix those pretty easily. I'm planning on using .box-dotted-lmagenta as the container.

Screenshot_20240712-202439_Firefox

I'm on a vacation so I'll not be very active for 8 days.

**Comment by Aesistril** [comment]
Oops merged to master by accident. I thought it would automatically create a new branch when I clicked "merge". It's fine for me though

**Comment by coolcat1711** [comment]
> Oops merged to master by accident. I thought it would automatically create a new branch when I clicked "merge". It's fine for me though

Could you actually make a "dev" branch or something available to merge into? That way I can make PR's against it and work on stuff without unfinished/mock-up work ending up in the mainline too early.

Probably good practice to keep "master" as the mainline that's good to push to the live website and "dev" as a place to keep things that are being worked on.

**Comment by Aesistril** [comment]
Done

**Pull request merged**
