### PR TITLE
DNS Page Updates

### PR DESCRIPTION
**Pull request by coolcat1711**
Adds a new page that details network/device DNS configuration.

Includes concept for an info box that lets you swap between Windows and Linux specific instructions.

### CODE REVIEW

**Comment by Aesistril** [comment]
content table on net config page is broken for mobile again but i'll fix it after the merge. Also it would be better if platform specific instructions were tabs instead of a single button

**Comment by Aesistril** [comment]
also I'm gonna add a "author" header on top of articles because I wanna give credit and also because of the license, CC BY-NC-SA, requires me to do so

**Comment by coolcat1711** [comment]
> content table on net config page is broken for mobile again but i'll fix it after the merge. Also it would be better if platform specific instructions were tabs instead of a single button

Have any thoughts on styling for tabs? I got something working with the buttons as intended but there's a lot of different ways to make that kind of thing look...

**Comment by Aesistril** [comment]
Multiple green buttons side by side is good enough i think. Similar to tabs in Haiku OS. You can reuse the green button for tabs

**Pull request merged**
