### PR TITLE
Began work on DNS Adblocking tutorial

### PR DESCRIPTION
**Pull request by coolcat1711**
Initial commit to solicit feedback and allow contributions.

May be worth making a new branch on the main fork to let people merge into before hosting on master.

### CODE REVIEW

**Comment by Aesistril** [comment]
Great guide. We will probably seperate the self hosting guide to another page

The main reason for this is because I wanna add a small box on top of guides about which skills the guide requires. For example we'll add "Requires basic UNIX skills" (hyperlinked to a unix/linux cli tutorial) on top of a guide which requires the user to install a service on a linux server or a raspberry pi.

Also I realized I used too much "me language" in guides so I'm probably gonna replace most of that with "we" 'cuz now i'm not the only one working on the project

**Comment by Aesistril** [comment]
I am merging this but as you said in the title, this is WIP. I'm also gonna upload some drafts I wrote in markdown

**Comment by coolcat1711** [comment]
> Great guide. We will probably seperate the self hosting guide to another page
> 
> The main reason for this is because I wanna add a small box on top of guides about which skills the guide requires. For example we'll add "Requires basic UNIX skills" (hyperlinked to a unix/linux cli tutorial) on top of a guide which requires the user to install a service on a linux server or a raspberry pi.

Do you want to use the main page then as a "primer page" with the actual how-to guides split out to their own pages with hyperlinks at the bottom of the "options" sections or something?

**Comment by Aesistril** [comment]
Well not really, but I just don't want the page length to be very long (mainly to avoid scaring people). But actually, this one can be left as one piece.

It's really a trade-off between continuity and psychological impact of long pages

I think we still should add a "requires unix skills" link after dns selfhosting the title. This way we can assume the user has basic cli skill.

What do you think?

**Comment by Aesistril** [comment]
I added some dns server recommendations i and some others on the net trust. It's not up on survival.aesistril.com yet. Are those alright?

**Comment by coolcat1711** [comment]
> Well not really, but I just don't want the page length to be very long (mainly to avoid scaring people). But actually, this one can be left as one piece.
> 
> It's really a trade-off between continuity and psychological impact of long pages
> 
> I think we still should add a "requires unix skills" link after dns selfhosting the title. This way we can assume the user has basic cli skill.
> 
> What do you think?

I think keeping things somewhat distinct will help keep newbies focused on things immediately relevant to them. While allowing more advanced guides for those who are interested and capable to be segmented from "mainline" content.

A choice to try and make upfront is who the intended audience is and how to manage the skill gap for those who aren't in that audience. Do we cater to absolute beginners and try to foster skill and understanding? Or do we cater to under-informed but technologically minded people? Because the writing style and skills cadence is going to change.

I'm almost envisioning some of these pages being something I can send to my mom/dad and expect them to be able to follow the instructions. Mass adoption of Ad blocking especially is important IMO because it sets the stage to show people that the internet *could* be better and it isn't due to deliberate choices by websites and corporations. Additionally, it establishes credibility for some of the more radical components relative to mainstream (Torrenting, FOSS ideology, using alternatives to mainstream software like LibreOffice or Linux in general). To be fair though, absolute newbies won't adopt a vast majority of this "curriculum" on their own systems without assistance. And to be fair, doing so is risky without someone to help keep systems clean and avoid obvious pitfalls.

This is a hard goal, but I also think it's where a lot of techy people lose support. It's easy to say "If they can't follow the guide, leave them behind" but we're going to need our whole communities in on this stuff to make real change for the better for everyone.

**Comment by Aesistril** [comment]
I thought about hosting a forum for techy people to make suggestions and for beginners to get support.

I get what you are saying. I know for most people tech isn't something they like but something they need

I've been successful teaching some of the stuff here (adblocking, torrenting, revanced...) to friends, sometimes in under an hour. So I have experience dealing with non-tech interested people.

About leaving people behind part, I don't expect people to read this guide from beginning to end like a book. For example, one can only read the torrenting part and be done with it. We are trying to capture as many people as possible with a verbose writing style, but it's still limited to people who are willing to read and experiment, not because they like it, but because it will make their lives instantly better

> I'm almost envisioning some of these pages being something I can send to my mom/dad and expect them to be able to follow the instructions. 

That's the goal yes. And agreed it's a hard one. My mom is someone who is non-techy but reads user manuals. I think I can ask her to do some end user testing sometime. (After I make extension install more verbose and add images to that one)

If you check the README.md, you can see there is another "TODO: advanced" seperate from regular TODO. That's because I'm planning on making a seperate guide (seperate site) for the "pro pc guys" (PCMR community?) audience. Mostly about self-hosting. I think that one will be easier since we will be working with a enthusiastic audience

**Comment by Aesistril** [comment]
I think having expandables can help with our goal of short, friendly tutorials. For example, we can have the repetitive sections like "how do i open the command line" under expandables. So only people who never read it will read it

**Pull request merged**
